server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  security:
    user:
      name: cho
      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"